apiVersion: v1
kind: Service
metadata:
  name: nodejsapi-service
spec:
  selector:
    app: nodejsapi
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: LoadBalancer